baseURL = "http://localhost:8080"
languageCode = "en-us"
title = "The Tudor Consort"
timeout = "60s"
enableRobotsTXT = true

# Allow HTML in Markdown
ignoreLogs = ['warning-goldmark-raw-html']
disableKinds = ["taxonomy"]

[params]
concertOffset = 0

[[build.cachebusters]]
source = 'layouts/.*'
target = 'scss'

[outputFormats]
[outputFormats.html]

# Allow raw HTML strings for images
isPlainText = true

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
