baseURL = "http://localhost:8080"
languageCode = "en-us"
title = "The Tudor Consort"
timeout = "60s"

# Allow HTML in Markdown
ignoreLogs = ['warning-goldmark-raw-html']

[[build.cachebusters]]
source = 'layouts/.*'
target = 'scss'

[outputFormats]
[outputFormats.html]

# Allow raw HTML strings for images
isPlainText = true
